### ISSUE TITLE
Syntax error for section

### ISSUE THREAD

**Issue by AndrewScholly** [PKCRY/PKCRY.github.io#9]
https://github.com/PKCRY/PKCRY.github.io/blob/3c98f12c9d0ae3c18c2fe0c4225a7293ca0cd472/index.html#L124
This should likely be a `<section>` instead of a `</section>`, as there is no beginning `<section>` for it nor the other one that follows it

**Comment by zachfedor** [comment]
@AndrewScholly, if you want to write an HTML tag, you need to surround it with a backtick. For example, this:
```
`<section>`
```
Turns into 
`<section>`

**Comment by AndrewScholly** [comment]
Is not an issue, made a mistake

**Comment by zachfedor** [comment]
then close, pls
